### ISSUE TITLE
add pictures

### ISSUE THREAD

**Issue by ccsouthard** [slang800/bellasurfaces.com#11]
- add additional pic of [lysha](https://www.yelp.com/biz_photos/bella-surfaces-north-billerica?select=IszgEg8ajTZMZMCu7gmSNA)
-  add [yelp](https://www.yelp.com/biz/bella-surfaces-north-billerica)  [badge](https://www.yelp.com/brand)

![yelp](https://user-images.githubusercontent.com/2887005/28086139-fd6e211e-664b-11e7-8058-fb6d131cb1ea.jpg)
![owners](https://user-images.githubusercontent.com/2887005/28086158-0fd6478c-664c-11e7-9bf9-32b859d3f8eb.jpg)

**Comment by ccsouthard** [comment]
`
<footer><div class="footer-column"><h3>About Us</h3><p>Bella Surfaces has over 20 years of combined experience in installing custom surfaces in Kitchens, Bathrooms, Playrooms and Commercial facilities throughout the New England area. Installations include countertops, bathroom vanities, bars, fireplaces, reception areas, commercial surfaces, and many, many more. We strive to offer the best customer service in combination with our courteous professional installation teams.</p>

<a title="Bella Surfaces BBB Business Review" href="http://www.bbb.org/boston/business-reviews/countertops/bella-surfaces-in-north-billerica-ma-131724">
<img alt="Bella Surfaces BBB Business Review" src="img/bbb-accredited-seal.svg"></a> <a title="Bella Surfaces Yelp Review" href="https://www.yelp.com/biz/bella-surfaces-north-billerica"><img class="float:left" alt="Bella Surfaces Yelp Review" src="img/yelp.jpg"></a></div>


<div class="footer-column"><h3>Vendors</h3><ul id="vendor-list">

<li><a href="http://www.avonitesurfaces.com/" title="Avonite Surfaces">Avonite Surfaces</a></li><li><a href="https://www.cambriausa.com/" title="Cambria® Natural Stone Surfaces">Cambria Surfaces</a></li><li><a href="http://www.caesarstoneus.com/" title="CaesarStone Quartz Surfaces">CaesarStone Quartz Surfaces</a></li><li><a href="http://www2.dupont.com/Surfaces/en_US/index.html" title="Dupont Zodiaq">Dupont Zodiaq</a></li><li><a href="http://www2.dupont.com/Corian_Global_Landing/en_US/index.html" title="DuPont™ Corian® ">DuPont™ Corian®</a></li><li><a href="http://www.lghausys.com/us/product/surfaces/sub_himacs.jsp" title="HI-MACS® Acrylic Solid Surface">HI-MACS® Acrylic Solid Surface</a></li><li><a href="http://www.quartzmasters.com/" title="Quartz Master">QuartzMaster</a></li><li><a href="http://www.silestoneusa.com/">SileStone</a></li><li><a href="http://www.lgviaterausa.com/" title="LG Viatera® Quartz Surface">LG Viatera Quartz Surface</a></li></ul></div
></footer>`

**Comment by ccsouthard** [comment]
<img src="about/owners.jpg" alt="">

- Added images of owners and yelp to image folders.

**Comment by notslang** [comment]
Can we get a better picture without the red-eye, phone in the shirt pocket, and background? Just have them go stand in front of a white wall and take one.

And where do you want these photos?

**Comment by ccsouthard** [comment]
I have requested but that's the best one I have. They have it on yelp. It's ugly – but they requested it go in there about section. The yelp badge needs to be next to the Better Business Bureau badge.
