### ISSUE TITLE
update vendor list

### ISSUE THREAD

**Issue by notslang** [slang800/bellasurfaces.com#13]
From earlier:

> - LG Viatera  
> - Silestone is one word 
> - Caesarstone is one word. 
> - Quartzmaster is also one word. 
> - remove Technistone 
> - remove Staron  

> ```
> <footer><div class="footer-column"><h3>About Us</h3><p>Bella Surfaces has over 20 years of combined experience in installing custom surfaces in Kitchens, Bathrooms, Playrooms and Commercial facilities throughout the New England area. Installations include countertops, bathroom vanities, bars, fireplaces, reception areas, commercial surfaces, and many, many more. We strive to offer the best customer service in combination with our courteous professional installation teams.</p>
> 
> <a title="Bella Surfaces BBB Business Review" href="http://www.bbb.org/boston/business-reviews/countertops/bella-surfaces-in-north-billerica-ma-131724">
> <img alt="Bella Surfaces BBB Business Review" src="img/bbb-accredited-seal.svg"></a> <a title="Bella Surfaces Yelp Review" href="https://www.yelp.com/biz/bella-surfaces-north-billerica"><img class="float:left" alt="Bella Surfaces Yelp Review" src="img/yelp.jpg"></a></div>
> 
> 
> <div class="footer-column"><h3>Vendors</h3><ul id="vendor-list">
> 
> <li><a href="http://www.avonitesurfaces.com/" title="Avonite Surfaces">Avonite Surfaces</a></li><li><a href="https://www.cambriausa.com/" title="Cambria® Natural Stone Surfaces">Cambria Surfaces</a></li><li><a href="http://www.caesarstoneus.com/" title="CaesarStone Quartz Surfaces">CaesarStone Quartz Surfaces</a></li><li><a href="http://www2.dupont.com/Surfaces/en_US/index.html" title="Dupont Zodiaq">Dupont Zodiaq</a></li><li><a href="http://www2.dupont.com/Corian_Global_Landing/en_US/index.html" title="DuPont™ Corian® ">DuPont™ Corian®</a></li><li><a href="http://www.lghausys.com/us/product/surfaces/sub_himacs.jsp" title="HI-MACS® Acrylic Solid Surface">HI-MACS® Acrylic Solid Surface</a></li><li><a href="http://www.quartzmasters.com/" title="Quartz Master">QuartzMaster</a></li><li><a href="http://www.silestoneusa.com/">SileStone</a></li><li><a href="http://www.lgviaterausa.com/" title="LG Viatera® Quartz Surface">LG Viatera Quartz Surface</a></li></ul></div
> ></footer>
> ```

Are you sure Quartzmaster is one word? Their website uses 2 words: http://www.quartzmasters.com/

**Comment by ccsouthard** [comment]
They Wanted it. Why I don't have an answer.

**Comment by notslang** [comment]
did you tell them about it?

**Comment by ccsouthard** [comment]
Let's leave it as two words.  It's so inconsequential – not worth the additional communication.
