### ISSUE TITLE
Add slide

### ISSUE THREAD

**Issue by ccsouthard** [slang800/bellasurfaces.com#2]
![kitch-granite](https://user-images.githubusercontent.com/2887005/27517909-3bbba826-59a2-11e7-9f76-cde2bbccb849.jpg)

**Comment by ccsouthard** [comment]
### Final Tweaks

1. Any images do you think that should be moved from the mockup to the production?
2. Footer to have body text on left and link text as above.
3. Contact info centered style w/fa like mockup
4. I think for UX  Purposes it makes sense to have a overlay for the inner portfolio pages. It requires two steps to get back. I think that's too much.
5. Hover effects for thumbnails
6. Kitchen, Baths, Bespoke, Fire  Should be the order of portfolio listed for going to stick to your idea and not have a sorting script.
7. Service pg should be 2 col like mockup
8. Style callout like mockup

  How are you updating the images?

**Comment by notslang** [comment]
slide is added in 7fdaf79403d48b2fa27227323d24d09c0099308e, other stuff should be moved into separate issues
