### ISSUE TITLE
"2 column" layout for service page 

### ISSUE THREAD

**Issue by notslang** [slang800/bellasurfaces.com#5]
Mockup looks like this:

![1498679709](https://user-images.githubusercontent.com/1049204/27657308-dc5caa70-5c11-11e7-98ae-b2c54ef00c26.png)

Waiting on images and additional content for staggered text layout.

**Comment by ccsouthard** [comment]
Let's use the current images that are there. I'll choose two more just for placement.  They won't correspond perfectly but they will be images.

**Comment by ccsouthard** [comment]
![absolute black kitchencountertops](https://user-images.githubusercontent.com/2887005/27657991-7c57cca8-5c1c-11e7-8d3f-3c501c2929d8.jpg)
![absolute black honed granite getting ready to be an island](https://user-images.githubusercontent.com/2887005/27658020-928b26a0-5c1c-11e7-944b-12ed31b74f53.jpg)

**Comment by ccsouthard** [comment]
http://www.bellasurfaces.com/wp-content/uploads/2012/05/auto_saw.jpg
http://www.bellasurfaces.com/wp-content/uploads/2012/05/299168_10150267667008335_203037773334_7733675_8172137_n.jpg

**Comment by notslang** [comment]
Do you have additional headings to add?

**Comment by ccsouthard** [comment]
template creation
 installation
 the final titles.

**Comment by notslang** [comment]
What? That doesn't fit with the content at all. I need 4 headings for the different sections to match your design.

**Comment by ccsouthard** [comment]
# Headings are as follows

Some are just accent photos. Are they ideal, no. Do they provide some context, yes. Are they stock? Pretty much for this site.

###### first row: Manufacturing 
 [saw](http://www.bellasurfaces.com/wp-content/uploads/2012/05/auto_saw.jpg)

###### second: Template Creation
[slab](https://user-images.githubusercontent.com/2887005/27658020-928b26a0-5c1c-11e7-944b-12ed31b74f53.jpg)

###### third: Customer Service
[soapstone island](http://www.bellasurfaces.com/wp-content/uploads/2012/05/299168_10150267667008335_203037773334_7733675_8172137_n.jpg)

###### fourth: Bring your Ideas 
[kitchen](https://user-images.githubusercontent.com/2887005/27657991-7c57cca8-5c1c-11e7-8d3f-3c501c2929d8.jpg)

**Comment by ccsouthard** [comment]
I think this looks good. Am I missing something?

**Comment by ccsouthard** [comment]
Done. Please close
