### ISSUE TITLE
changing portfolio category order

### ISSUE THREAD

**Issue by notslang** [slang800/bellasurfaces.com#6]
From chat:

> The thumbnail list. What I'm referring to in terms of the categories is the way they are presented. I think that kitchens should go first and then bathrooms etc. right now it looks awkward with only two thumbnails at the start. Can we add some cool hover effects?

Right now they're sorted alphabetically by name (bathrooms, bespoke, fireplace hearths, kitchens). We could switch to sorting by the number of entries or something like that, but if we have categories with only 1-2 items in them, then we should probably get more items, or drop those categories altogether.

**Comment by ccsouthard** [comment]
Sure sounds good.

**Comment by notslang** [comment]
Which option? Sorting by number of items per category, dropping the categories that are too small, or do you not care?

**Comment by ccsouthard** [comment]
Leave as is to save time
